#name: Telegram Notification
name: TelegramNtfctn
on:
  push:
    branches:
      - main

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification
      #uses: appleboy/telegram-action@v0.2.0
      #uses: anemusudha/telegram-action@v0.2.0
      #uses: appleboy/telegram-action@v1
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          Hara hara mahadev!!!!! This notification is from Github Actions buddy..
          From the yml : telegram-notifications
          Commit message: ${{ github.event.head_commit.message }}
          Committer: ${{ github.event.head_commit.author.name }}
          Repository: ${{ github.repository }}
