# This is a basic workflow to help you get started with Actions

name: WorkflowRun

on:
  workflow_run:
    workflows: [CI,TelegramNtfctn]
    types: [completed]

    #workflows: [TelegramNtfctn]
    #types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'